apiVersion: v1
data:
  tokens.json: W3sidG9rZW4iOiAiYmVuY2htYXJrIn1d
  whitelist: e19fbmFtZV9fPSJ1cCJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uIn0Ke19fbmFtZV9fPSJjbHVzdGVyX3ZlcnNpb25fYXZhaWxhYmxlX3VwZGF0ZXMifQp7X19uYW1lX189ImNsdXN0ZXJfb3BlcmF0b3JfdXAifQp7X19uYW1lX189ImNsdXN0ZXJfb3BlcmF0b3JfY29uZGl0aW9ucyJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uX3BheWxvYWQifQp7X19uYW1lX189ImNsdXN0ZXJfdmVyc2lvbl9wYXlsb2FkX2Vycm9ycyJ9CntfX25hbWVfXz0iY2x1c3Rlcl9pbnN0YWxsZXIifQp7X19uYW1lX189Imluc3RhbmNlOmV0Y2Rfb2JqZWN0X2NvdW50czpzdW0ifQp7X19uYW1lX189ImFsZXJ0cyIsYWxlcnRzdGF0ZT0iZmlyaW5nIn0Ke19fbmFtZV9fPSJjb2RlOmFwaXNlcnZlcl9yZXF1ZXN0X2NvdW50OnJhdGU6c3VtIn0Ke19fbmFtZV9fPSJrdWJlX3BvZF9zdGF0dXNfcmVhZHk6ZXRjZDpzdW0ifQp7X19uYW1lX189Imt1YmVfcG9kX3N0YXR1c19yZWFkeTppbWFnZV9yZWdpc3RyeTpzdW0ifQp7X19uYW1lX189ImNsdXN0ZXI6Y2FwYWNpdHlfY3B1X2NvcmVzOnN1bSJ9CntfX25hbWVfXz0iY2x1c3RlcjpjYXBhY2l0eV9tZW1vcnlfYnl0ZXM6c3VtIn0Ke19fbmFtZV9fPSJjbHVzdGVyOmNwdV91c2FnZV9jb3JlczpzdW0ifQp7X19uYW1lX189ImNsdXN0ZXI6bWVtb3J5X3VzYWdlX2J5dGVzOnN1bSJ9CntfX25hbWVfXz0ib3BlbnNoaWZ0OmNwdV91c2FnZV9jb3JlczpzdW0ifQp7X19uYW1lX189Im9wZW5zaGlmdDptZW1vcnlfdXNhZ2VfYnl0ZXM6c3VtIn0Ke19fbmFtZV9fPSJjbHVzdGVyOm5vZGVfaW5zdGFuY2VfdHlwZV9jb3VudDpzdW0ifQ==
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: telemeter-benchmark
type: Opaque
