apiVersion: v1
data:
  tokens.json: W3sidG9rZW4iOiAiYmVuY2htYXJrIn1d
  whitelist: e19fbmFtZV9fPSJ1cCJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uIn0Ke19fbmFtZV9fPSJjbHVzdGVyX3ZlcnNpb25fYXZhaWxhYmxlX3VwZGF0ZXMifQp7X19uYW1lX189ImNsdXN0ZXJfb3BlcmF0b3JfdXAifQp7X19uYW1lX189ImNsdXN0ZXJfb3BlcmF0b3JfY29uZGl0aW9ucyJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uX3BheWxvYWQifQp7X19uYW1lX189ImNsdXN0ZXJfaW5zdGFsbGVyIn0Ke19fbmFtZV9fPSJpbnN0YW5jZTpldGNkX29iamVjdF9jb3VudHM6c3VtIn0Ke19fbmFtZV9fPSJhbGVydHMiLGFsZXJ0c3RhdGU9ImZpcmluZyJ9CntfX25hbWVfXz0iY29kZTphcGlzZXJ2ZXJfcmVxdWVzdF9jb3VudDpyYXRlOnN1bSJ9CntfX25hbWVfXz0iY2x1c3RlcjpjYXBhY2l0eV9jcHVfY29yZXM6c3VtIn0Ke19fbmFtZV9fPSJjbHVzdGVyOmNhcGFjaXR5X21lbW9yeV9ieXRlczpzdW0ifQp7X19uYW1lX189ImNsdXN0ZXI6Y3B1X3VzYWdlX2NvcmVzOnN1bSJ9CntfX25hbWVfXz0iY2x1c3RlcjptZW1vcnlfdXNhZ2VfYnl0ZXM6c3VtIn0Ke19fbmFtZV9fPSJvcGVuc2hpZnQ6Y3B1X3VzYWdlX2NvcmVzOnN1bSJ9CntfX25hbWVfXz0ib3BlbnNoaWZ0Om1lbW9yeV91c2FnZV9ieXRlczpzdW0ifQp7X19uYW1lX189ImNsdXN0ZXI6bm9kZV9pbnN0YW5jZV90eXBlX2NvdW50OnN1bSJ9CntfX25hbWVfXz0iY252OnZtaV9zdGF0dXNfcnVubmluZzpjb3VudCJ9CntfX25hbWVfXz0ic3Vic2NyaXB0aW9uX3N5bmNfdG90YWwifQ==
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: telemeter-benchmark
type: Opaque
