apiVersion: v1
kind: Template
metadata:
  name: telemeter
objects:
- apiVersion: v1
  data:
    rhd.client_id: ""
    rhd.password: ""
    rhd.url: ""
    rhd.username: ""
    whitelist: e19fbmFtZV9fPSJ1cCJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uIn0Ke19fbmFtZV9fPSJjbHVzdGVyX29wZXJhdG9yX3VwIn0Ke19fbmFtZV9fPSJjbHVzdGVyX29wZXJhdG9yX2NvbmRpdGlvbnMifQp7X19uYW1lX189ImNsdXN0ZXJfdmVyc2lvbl9wYXlsb2FkIn0Ke19fbmFtZV9fPSJjbHVzdGVyX3ZlcnNpb25fcGF5bG9hZF9lcnJvcnMifQp7X19uYW1lX189Im1hY2hpbmVfY3B1X2NvcmVzIn0Ke19fbmFtZV9fPSJtYWNoaW5lX21lbW9yeV9ieXRlcyJ9CntfX25hbWVfXz0iZXRjZF9vYmplY3RfY291bnRzIn0Ke19fbmFtZV9fPSJhbGVydHMiLGFsZXJ0c3RhdGU9ImZpcmluZyJ9
  kind: Secret
  metadata:
    labels:
      k8s-app: telemeter-server
    name: telemeter-server
    namespace: ${NAMESPACE}
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: telemeter-server-shared
    labels:
      k8s-app: telemeter-server
    name: telemeter-server
    namespace: ${NAMESPACE}
  spec:
    clusterIP: None
    ports:
    - name: external
      port: 8443
      targetPort: external
    - name: internal
      port: 8081
      targetPort: internal
    - name: cluster
      port: 8082
      targetPort: cluster
    selector:
      k8s-app: telemeter-server
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: telemeter-server
    namespace: ${NAMESPACE}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      endpoint: metrics
      k8s-app: telemeter-server
    name: telemeter-server
    namespace: ${NAMESPACE}
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: internal
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        serverName: telemeter-server.${NAMESPACE}.svc
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: telemeter-server
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      endpoint: federate
      k8s-app: telemeter-server
    name: telemeter-server-federate
    namespace: ${NAMESPACE}
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      interval: 15s
      params:
        match[]:
        - '{__name__=~".*"}'
      path: /federate
      port: internal
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        serverName: telemeter-server.${NAMESPACE}.svc
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: telemeter-server
- apiVersion: apps/v1beta2
  kind: StatefulSet
  metadata:
    name: telemeter-server
    namespace: ${NAMESPACE}
  spec:
    podManagementPolicy: Parallel
    replicas: 10
    selector:
      matchLabels:
        k8s-app: telemeter-server
    serviceName: telemeter-server
    template:
      metadata:
        labels:
          k8s-app: telemeter-server
      spec:
        containers:
        - command:
          - /usr/bin/telemeter-server
          - --join=telemeter-server
          - --name=$(NAME)
          - --listen=0.0.0.0:8443
          - --listen-internal=0.0.0.0:8081
          - --listen-cluster=0.0.0.0:8082
          - --shared-key=/etc/pki/service/tls.key
          - --tls-key=/etc/pki/service/tls.key
          - --tls-crt=/etc/pki/service/tls.crt
          - --internal-tls-key=/etc/pki/service/tls.key
          - --internal-tls-crt=/etc/pki/service/tls.crt
          - --authorize=${AUTHORIZE_URL}
          - --authorize-issuer-url=$(RHD_URL)
          - --authorize-client-id=$(RHD_CLIENT_ID)
          - --authorize-username=$(RHD_USERNAME)
          - --authorize-password=$(RHD_PASSWORD)
          - --whitelist-file=/etc/telemeter/whitelist
          env:
          - name: NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RHD_URL
            valueFrom:
              secretKeyRef:
                key: rhd.url
                name: telemeter-server
          - name: RHD_USERNAME
            valueFrom:
              secretKeyRef:
                key: rhd.username
                name: telemeter-server
          - name: RHD_PASSWORD
            valueFrom:
              secretKeyRef:
                key: rhd.password
                name: telemeter-server
          - name: RHD_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: rhd.client_id
                name: telemeter-server
          image: ${IMAGE}:${IMAGE_TAG}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          name: telemeter-server
          ports:
          - containerPort: 8443
            name: external
          - containerPort: 8081
            name: internal
          - containerPort: 8082
            name: cluster
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8443
              scheme: HTTPS
          volumeMounts:
          - mountPath: /etc/telemeter
            name: secret-telemeter-server
            readOnly: false
          - mountPath: /etc/pki/service
            name: telemeter-server-tls
            readOnly: false
        serviceAccountName: telemeter-server
        volumes:
        - name: secret-telemeter-server
          secret:
            secretName: telemeter-server
        - name: telemeter-server-tls
          secret:
            secretName: telemeter-server-shared
parameters:
- name: AUTHORIZE_URL
  value: https://api.openshift.com/api/accounts_mgmt/v1/cluster_registrations
- name: NAMESPACE
  value: telemeter
- name: IMAGE
  value: quay.io/openshift/origin-telemeter
- name: IMAGE_TAG
  value: v4.0
