apiVersion: v1
data:
  rhd.client_id: ""
  rhd.password: ""
  rhd.url: ""
  rhd.username: ""
  whitelist: e19fbmFtZV9fPSJ1cCJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uIn0Ke19fbmFtZV9fPSJjbHVzdGVyX29wZXJhdG9yX3VwIn0Ke19fbmFtZV9fPSJjbHVzdGVyX29wZXJhdG9yX2NvbmRpdGlvbnMifQp7X19uYW1lX189ImNsdXN0ZXJfdmVyc2lvbl9wYXlsb2FkIn0Ke19fbmFtZV9fPSJjbHVzdGVyX3ZlcnNpb25fcGF5bG9hZF9lcnJvcnMifQp7X19uYW1lX189Im1hY2hpbmVfY3B1X2NvcmVzIn0Ke19fbmFtZV9fPSJtYWNoaW5lX21lbW9yeV9ieXRlcyJ9CntfX25hbWVfXz0iZXRjZF9vYmplY3RfY291bnRzIn0Ke19fbmFtZV9fPSJhbGVydHMiLGFsZXJ0c3RhdGU9ImZpcmluZyJ9CntfX25hbWVfXz0icG9kOmt1YmVfcG9kX2NvbnRhaW5lcl9zdGF0dXNfcnVubmluZyJ9CntfX25hbWVfXz0icG9kOmt1YmVfcG9kX2NvbnRhaW5lcl9zdGF0dXNfdGVybWluYXRlZCJ9CntfX25hbWVfXz0icG9kOmt1YmVfcG9kX2NvbnRhaW5lcl9zdGF0dXNfcmVzdGFydHNfdG90YWwifQp7X19uYW1lX189InBvZDprdWJlX3BvZF9jb250YWluZXJfc3RhdHVzX3Rlcm1pbmF0ZWRfcmVhc29uIn0=
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: telemeter
type: Opaque
