apiVersion: v1
data:
  anonymizeLabels: ""
  match-rules: e19fbmFtZV9fPSJ1cCJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uIn0Ke19fbmFtZV9fPSJjbHVzdGVyX29wZXJhdG9yX3VwIn0Ke19fbmFtZV9fPSJjbHVzdGVyX29wZXJhdG9yX2NvbmRpdGlvbnMifQp7X19uYW1lX189ImNsdXN0ZXJfdmVyc2lvbl9wYXlsb2FkIn0Ke19fbmFtZV9fPSJjbHVzdGVyX3ZlcnNpb25fcGF5bG9hZF9lcnJvcnMifQp7X19uYW1lX189Im1hY2hpbmVfY3B1X2NvcmVzIn0Ke19fbmFtZV9fPSJtYWNoaW5lX21lbW9yeV9ieXRlcyJ9CntfX25hbWVfXz0iZXRjZF9vYmplY3RfY291bnRzIn0Ke19fbmFtZV9fPSJBTEVSVFMiLGFsZXJ0c3RhdGU9ImZpcmluZyJ9CntfX25hbWVfXz0ibm9kZTpub2RlX2NwdV91dGlsaXNhdGlvbjphdmcxbSJ9CntfX25hbWVfXz0ibm9kZTpub2RlX21lbW9yeV91dGlsaXNhdGlvbjpyYXRpbyJ9CntfX25hbWVfXz0ibm9kZV9maWxlc3lzdGVtX3NpemVfYnl0ZXMifQp7X19uYW1lX189Im5vZGU6bm9kZV9kaXNrX3V0aWxpc2F0aW9uOmF2Z19pcmF0ZSJ9
  salt: ""
  to: aHR0cHM6Ly9pbmZvZ3cuYXBpLm9wZW5zaGlmdC5jb20=
  token: ""
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-client
  name: telemeter-client
  namespace: openshift-monitoring
type: Opaque
